//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hostel_allocation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Block
    {
        public int Id { get; set; }
        public int Hostel_id { get; set; }
        public string name { get; set; }
    }
}
