//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hostel_allocation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hostelEntities2 : DbContext
    {
        public hostelEntities2()
            : base("name=hostelEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Block> Blocks { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Hostel> Hostels { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Space> Spaces { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Reciept> Reciept { get; set; }
    }
}
