//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hostel_allocation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reciept
    {
        public int Id { get; set; }
        public string Category { get; set; }
        public string Ticket_number { get; set; }
        public int Payer { get; set; }
        public int Amount { get; set; }
        public System.DateTime Ticket_created { get; set; }
        public string Item { get; set; }
        public string Level { get; set; }
        public Nullable<System.DateTime> Payment_date { get; set; }
        public string Payment_state { get; set; }
        public string Payment_gateway { get; set; }
        public string Response_card_Number { get; set; }
        public string Response_Description { get; set; }
        public string Response_code { get; set; }
        public string Session { get; set; }
    }
}
