//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hostel_allocation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Space
    {
        public int Id { get; set; }
        public string Corner { get; set; }
        public int Room_id { get; set; }
        public Nullable<int> Student_id { get; set; }
        public Nullable<bool> Cleared { get; set; }
    }
}
